In [3]:
import pandas as pd
import numpy as np

In [4]:
# Reading csv file from url
df=pd.read_csv('http://13.234.66.67/summer19/datasets/info.csv')


In [5]:
df
df.describe()     # Tells count, mean, std

Country   Age   Salary Purchased
0   France  44.0  72000.0        No
1    Spain  27.0  48000.0       Yes
2  Germany  30.0  54000.0        No
3    Spain  38.0  61000.0        No
4  Germany  40.0      NaN       Yes
5   France  35.0  58000.0       Yes
6    Spain   NaN  52000.0        No
7   France  48.0  79000.0       Yes
8  Germany  50.0  83000.0        No
9   France  37.0  67000.0       Yes

In [11]:
#
x=df.iloc[:,0:3].values    # removing header of data by .values
# Removing missing value / replacing missing value with relevant data
from sklearn.preprocessing import Imputer
x

array([['France', 44.0, 72000.0],
       ['Spain', 27.0, 48000.0],
       ['Germany', 30.0, 54000.0],
       ['Spain', 38.0, 61000.0],
       ['Germany', 40.0, nan],
       ['France', 35.0, 58000.0],
       ['Spain', nan, 52000.0],
       ['France', 48.0, 79000.0],
       ['Germany', 50.0, 83000.0],
       ['France', 37.0, 67000.0]], dtype=object)

In [23]:
#Shift+Tab
imp=Imputer(missing_values='NaN',axis=0,strategy='mean')  # axis=0 means apply on column

In [24]:
impute=imp.fit(x[:,1:3])  # only fitting columns that we want to process
# imp.fit get to know that on which colms data cleaning is to be performed
x[:,1:3]=impute.transform(x[:,1:3])  # transform will change the data i.e replace it with mean
x

array([[0, 44.0, 7.0],
       [2, 27.0, 0.0],
       [1, 30.0, 2.0],
       [2, 38.0, 4.0],
       [1, 40.0, 5.0],
       [0, 35.0, 3.0],
       [2, 38.77777777777778, 1.0],
       [0, 48.0, 8.0],
       [1, 50.0, 9.0],
       [0, 37.0, 6.0]], dtype=object)

In [25]:
# Missing values removed successfully

# For replacing numerical missing value we can use imputer

# For replacing string with the numerical values
from sklearn.preprocessing import LabelEncoder


In [17]:
cont=LabelEncoder()  # This is for changing country labeling with int value

# Apply column first in this LabelEn
x[:,0]=cont.fit_transform(x[:,0])
x

array([[0, 44.0, 72000.0],
       [2, 27.0, 48000.0],
       [1, 30.0, 54000.0],
       [2, 38.0, 61000.0],
       [1, 40.0, 63777.77777777778],
       [0, 35.0, 58000.0],
       [2, 38.77777777777778, 52000.0],
       [0, 48.0, 79000.0],
       [1, 50.0, 83000.0],
       [0, 37.0, 67000.0]], dtype=object)

In [26]:
# France =0 , Spain=2, Germany=1
#Labeling last column
p=LabelEncoder()
x[:,3]=p.fit_transform(x[:,3])
x

IndexError: index 3 is out of bounds for axis 1 with size 3

In [27]:
# we have replaced countries with 1,2 and 3
'''When KNN will be applied and difference will be calculated then bcz pf this numbering algo can treat
a country superior than other which is not good , so we do the following
Freance | Spain | Germany
1       |0      |0    
0       |1      |0             This is known as encoding'''



'When KNN will be applied and difference will be calculated then bcz pf this numbering algo can treat\na country superior than other which is not good , so we do the following\nFreance | Spain | Germany\n1       |0      |0    \n0       |1      |0             This is known as encoding'

In [30]:
#features scaling -- making features compatible with each other,, bring them in equal range

# Now encoding first col -- making sub column of first col
from sklearn.preprocessing import OneHotEncoder

In [35]:
firstcl=OneHotEncoder(categorical_features=[0])  # 0 is col no. for country


In [36]:
x=firstcl.fit_transform(x)   # We have mention col above so give complete data here

In [38]:
x.toarray()
# OR   x=firstcl.fit_transform(x).toarray()
#      x.astype(int)   to show as integer

array([[ 1.        ,  0.        ,  0.        , 44.        ,  7.        ],
       [ 0.        ,  0.        ,  1.        , 27.        ,  0.        ],
       [ 0.        ,  1.        ,  0.        , 30.        ,  2.        ],
       [ 0.        ,  0.        ,  1.        , 38.        ,  4.        ],
       [ 0.        ,  1.        ,  0.        , 40.        ,  5.        ],
       [ 1.        ,  0.        ,  0.        , 35.        ,  3.        ],
       [ 0.        ,  0.        ,  1.        , 38.77777778,  1.        ],
       [ 1.        ,  0.        ,  0.        , 48.        ,  8.        ],
       [ 0.        ,  1.        ,  0.        , 50.        ,  9.        ],
       [ 1.        ,  0.        ,  0.        , 37.        ,  6.        ]])

In [ ]:
'''1- Imputer
   2- Label Encoding
   3- OneHotEncoder'''